version: "3.5" # specify docker-compose version

# Define the services/containers to be run
services:
  smms-angular-app-prod: # name of the first service
    build:
      context: ./angular-app # specify the directory of the Dockerfile
      dockerfile: Dockerfile-prod

    ports:
      - 80:80 # specify port forewarding

  smms-node-app: #name of the second service
    container_name: smms-node-app
    build: ./node-app # specify the directory of the Dockerfile
    ports:
      - 3000:3000 #specify ports forewarding
    volumes:
      - ./node-app:/usr/src/app
    command: >
      bash -c "npm start --host 0.0.0.0 -port 3000"
